id: P7B8ECEA7
initial_creation_type: input
source_metadata:
  title: Thönmi Sambhoṭa Series
  language: bo
  description: 'Texts by and about Thönmi Sambhoṭa, who is credited with inventing
    the Tibetan writing system and composing the country''s first grammatical treatises:'
  volume:
    0137ef3df7b64302bdf9f98c9194f53a:
      title: 'A Blossoming of the Intellect: In Praise of the Great Pioneer Thönmi
        Sambhoṭa'
      parent: Praise
created_at: '2022-03-01T01:48:50.474334'
last_modified_at: '2022-03-01T01:48:50.474337'
